# Imports

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import time
import pickle
from collections import deque

In [8]:
alpha=0.01
alpha_decay=0.01
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(24, input_dim=5, activation='tanh')) # input the 5 dimensions of the state
model.add(tf.keras.layers.Dense(48, activation='tanh'))
model.add(tf.keras.layers.Dense(2, activation='linear')) # output the Q-values (value function) for the two actions

optimizer=keras.optimizers.Adam(learning_rate=alpha, decay=alpha_decay)
loss = keras.losses.MeanSquaredError()
model.compile(optimizer=optimizer, loss=loss)

In [9]:
state = np.array([[1,1,1,1,0]])

In [10]:
start = time.time()
np.argmax(model.predict(state))
print(time.time()-start)

0.09399867057800293


In [27]:
PATH = "C:/Users/tomas/Desktop/summer projects/game/RL/agents/"
mem = pickle.load(open(f"{PATH}{210623}_{1609}.p", "rb"))

In [30]:
episode = [mem[0]]

(array([[200, 200,  10,  -1,  10]]),
 0,
 0,
 array([[190, 199,  20,  -1,  10]]),
 False)

In [33]:
episode = []
for m in mem:
    episode.append(m[0])
    if m[4]:
        break

In [34]:
episode

[array([[200, 200,  10,  -1,  10]]),
 array([[190, 199,  20,  -1,  10]]),
 array([[200, 198,  30,  -1,  10]]),
 array([[190, 197,  40,  -1,  10]]),
 array([[180, 196,  50,  -1,  10]]),
 array([[170, 195,  60,  -1,  10]]),
 array([[160, 194,  70,  -1,  10]]),
 array([[150, 193,  80,  -1,  10]]),
 array([[140, 192,  90,  -1,  10]]),
 array([[130, 191, 100,  -1,  10]]),
 array([[120, 190, 110,  -1,  10]]),
 array([[110, 189, 120,  -1,  10]]),
 array([[100, 188, 130,  -1,  10]]),
 array([[100, 187, 140,  -1,  10]]),
 array([[100, 186, 150,  -1,  10]]),
 array([[100, 185, 160,  -1,  10]]),
 array([[100, 184, 170,  -1,  10]]),
 array([[100, 183, 180,  -1,  10]]),
 array([[100, 182, 190,  -1,  10]]),
 array([[100, 181, 200,  -1,  10]]),
 array([[100, 180, 210,  -1,  10]]),
 array([[110, 179, 220,  -1,  10]]),
 array([[120, 178, 230,  -1,  10]]),
 array([[130, 177, 240,  -1,  10]]),
 array([[140, 176, 250,  -1,  10]]),
 array([[150, 175, 260,  -1,  10]]),
 array([[160, 174, 270,  -1,  10]]),
 